#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
_('report field template')
_('ReportFieldTemplate|Applicable on')
_('ReportFieldTemplate|Function')
_('ReportFieldTemplate|Render method')
_('ReportFieldTemplate|Render options')
_('ReportFieldTemplate|Name')
_('region')
_('Region|Name')
_('odat diagnosis')
_('OdatDiagnosis|Description')
_('OdatDiagnosis|Description html')
_('job')
_('Job|Name')
_('Job|Description')
_('Job|Position')
_('Job|Description html')
_('job status')
_('JobStatus|Name')
_('JobStatus|Description')
_('JobStatus|Position')
_('JobStatus|Description html')
_('consultation cause')
_('ConsultationCause|Name')
_('ConsultationCause|Description')
_('ConsultationCause|Position')
_('ConsultationCause|Description html')
_('province')
_('Province|Name')
_('comparative report field template assignment')
_('ComparativeReportFieldTemplateAssignment|Position')
_('ComparativeReportFieldTemplateAssignment|Name')
_('ComparativeReportFieldTemplateAssignment|Group')
_('comparative report template field assignment')
_('ComparativeReportTemplateFieldAssignment|Position')
_('ComparativeReportTemplateFieldAssignment|Name')
_('ComparativeReportTemplateFieldAssignment|Group')
_('school type')
_('SchoolType|Name')
_('SchoolType|Description')
_('SchoolType|Description html')
_('civil state')
_('CivilState|Name')
_('CivilState|Description')
_('CivilState|Position')
_('CivilState|Description html')
_('page')
_('Page|Title')
_('Page|Permalink')
_('Page|Sidebar content')
_('Page|Sidebar content html')
_('Page|Content')
_('Page|Content html')
_('origin cause')
_('OriginCause|Name')
_('OriginCause|Description')
_('OriginCause|Position')
_('OriginCause|Description html')
_('individual report')
_('IndividualReport|Topic')
_('IndividualReport|Topic html')
_('IndividualReport|Tests')
_('IndividualReport|Tests html')
_('IndividualReport|Results')
_('IndividualReport|Results html')
_('IndividualReport|Orientation')
_('IndividualReport|Orientation html')
_('IndividualReport|Signature')
_('IndividualReport|Signed on')
_('IndividualReport|Show signature')
_('IndividualReport|Show signed on')
_('IndividualReport|Show medical record archive date')
_('IndividualReport|Show birth date')
_('IndividualReport|Show age')
_('IndividualReport|Show full name')
_('IndividualReport|Show gender')
_('IndividualReport|Show birth position')
_('IndividualReport|Show address')
_('IndividualReport|Show siblings data')
_('IndividualReport|Show father data')
_('IndividualReport|Show mother data')
_('IndividualReport|Show phone numbers')
_('IndividualReport|Show diagnosis created at')
_('IndividualReport|Show consultation details')
_('IndividualReport|Show center resources')
_('IndividualReport|Show detailed diagnosis')
_('IndividualReport|Show coordination services')
_('IndividualReport|Show main diagnosis')
_('IndividualReport|Extra information')
_('IndividualReport|Extra information html')
_('IndividualReport|Show handicap data')
_('IndividualReport|Show level3')
_('comparative report')
_('ComparativeReport|Show signature')
_('ComparativeReport|Signature')
_('ComparativeReport|Show signed on')
_('ComparativeReport|Signed on')
_('ComparativeReport|Extra information')
_('ComparativeReport|Extra information html')
_('center resource')
_('CenterResource|Name')
_('CenterResource|Description')
_('CenterResource|Position')
_('CenterResource|Description html')
_('user')
_('User|Login')
_('User|Email')
_('User|Crypted password')
_('User|Password salt')
_('User|Persistence token')
_('User|Perishable token')
_('User|Login count')
_('User|Failed login count')
_('User|Last request at')
_('User|Last login at')
_('User|Current login at')
_('User|Last login ip')
_('User|Current login ip')
_('User|Active')
_('User|Approved')
_('User|Confirmed')
_('User|Role')
_('User|Name')
_('center')
_('Center|Name')
_('diagnosis item')
_('DiagnosisItem|Name')
_('DiagnosisItem|Description')
_('DiagnosisItem|Description html')
_('DiagnosisItem|Lft')
_('DiagnosisItem|Rgt')
_('DiagnosisItem|Multiple select')
_('DiagnosisItem|Classification level')
_('report')
_('Report|Show signature')
_('Report|Signature')
_('Report|Show signed on')
_('Report|Signed on')
_('Report|Extra information')
_('Report|Extra information html')
_('origin source')
_('OriginSource|Name')
_('OriginSource|Description')
_('OriginSource|Position')
_('OriginSource|Description html')
_('medical record')
_('MedicalRecord|Name')
_('MedicalRecord|Surname')
_('MedicalRecord|Birth date')
_('MedicalRecord|Archive date')
_('MedicalRecord|City')
_('MedicalRecord|Address')
_('MedicalRecord|Birth position')
_('MedicalRecord|Gender')
_('MedicalRecord|Father name')
_('MedicalRecord|Father surname')
_('MedicalRecord|Father birth date')
_('MedicalRecord|Father email')
_('MedicalRecord|Father extra information')
_('MedicalRecord|Mother name')
_('MedicalRecord|Mother surname')
_('MedicalRecord|Mother birth date')
_('MedicalRecord|Mother email')
_('MedicalRecord|Mother extra information')
_('MedicalRecord|Home phone')
_('MedicalRecord|Portable phone')
_('MedicalRecord|Work phone')
_('MedicalRecord|Total siblings amount')
_('MedicalRecord|Postal')
_('MedicalRecord|Sanitary services')
_('MedicalRecord|Social services')
_('MedicalRecord|Educative services')
_('MedicalRecord|Multiple birth')
_('MedicalRecord|Position in siblings')
_('MedicalRecord|Handicap')
_('MedicalRecord|Dependency degree')
_('formation level')
_('FormationLevel|Name')
_('FormationLevel|Description')
_('FormationLevel|Position')
_('FormationLevel|Description html')
_('configurable view')
_('ConfigurableView|Font size')
_('ConfigurableView|Font family')
_('ConfigurableView|Table grid')
_('comparative report template')
_('ComparativeReportTemplate|Name')
_('ComparativeReportTemplate|Title')
_('ComparativeReportTemplate|View template')
#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
